### ISSUE TITLE
Performance of Groupby

### ISSUE THREAD

**Issue by jlou2u** [esantorella/hdfe#2]
I found your blog post (http://esantorella.com/2016/06/16/groupby/) and was initially intrigued about being able to increase performance of user defined functions in groupby.  But looking more closely I think you're just comparing a lazy function to a strict one.  I don't see any difference in speed in terms of applying the functions to groups.

using the example from your blog, it think this shows most clearly what i mean:

In [30]: %timeit Groupby(df["first category"])      
5.79 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [31]: %timeit df.groupby("first category")       
55.8 µs ± 3.99 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

pandas groupby is lazy and does essentially nothing until you apply some function.  your groupby does work in __init__ to setup the groups.

Does that seem correct or am I missing how to speed up applying functions to groups?

**Comment by tbenthompson** [comment]
Hi, if I understand what you're saying correctly, you're pointing out that it isn't fair to compare Pandas DataFrame.groupby.apply to my Groupby.apply because Pandas, being lazy here, saved time in the 'groupby' call that it later has to do in the 'apply' call. This is true, but the benchmarks provided take this into account by counting the time from setting up the groups. Example:

%timeit Groupby(df['first category'].values).apply(np.mean, df['y'].values, False)
11.3 ms ± 194 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit df.groupby('first category')['y'].apply(np.mean)
118 ms ± 4.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Let me know if I'm misunderstanding your question.

**Comment by esantorella** [comment]
Hi, if I understand what you're saying correctly, you're pointing out that it isn't fair to compare Pandas DataFrame.groupby.apply to my Groupby.apply because Pandas, being lazy here, saved time in the 'groupby' call that it later has to do in the 'apply' call. This is true, but the benchmarks provided take this into account by counting the time from setting up the groups. Example:

%timeit Groupby(df['first category'].values).apply(np.mean, df['y'].values, False)
11.3 ms ± 194 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit df.groupby('first category')['y'].apply(np.mean)
118 ms ± 4.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Let me know if I'm misunderstanding your question. (And sorry, I just replied to this from the wrong account and deleted!)
